/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ribbonstarter;

import javax.swing.JDialog;

/**
 *
 * @author s.nepochatov
 */
public class StarterFrame extends javax.swing.JFrame {

    /**
     * Creates new form StarterFrame
     */
    public StarterFrame() {
        initComponents();
    }
    
    /**
     * Append string message to the journal;
     * @param message string to append;
     */
    public void appendToLog(String message) {
        this.journalText.append(message + System.lineSeparator());
        this.journalText.setCaretPosition(this.journalText.getText().length());
    }
    
    /**
     * Set execution displaying in starter window;
     * @param flag flag of execution (true - execution run, false execution stopped);
     */
    public void setExecution(Boolean flag) {
        if (flag) {
            this.startBut.setEnabled(false);
            this.journalText.setText("");
            this.stopBut.setEnabled(true);
            this.propertiesBut.setEnabled(false);
        } else {
            this.startBut.setEnabled(true);
            this.stopBut.setEnabled(false);
            this.propertiesBut.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        journalText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        startBut = new javax.swing.JButton();
        stopBut = new javax.swing.JButton();
        propertiesBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Стратер серверу \"Стрічка\"");

        journalText.setColumns(20);
        journalText.setEditable(false);
        journalText.setRows(5);
        jScrollPane1.setViewportView(journalText);

        jLabel1.setText("Журнал сервера");

        startBut.setForeground(new java.awt.Color(0, 102, 0));
        startBut.setText("Запустити");
        startBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButActionPerformed(evt);
            }
        });

        stopBut.setForeground(new java.awt.Color(102, 0, 0));
        stopBut.setText("Зупинити");
        stopBut.setEnabled(false);
        stopBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButActionPerformed(evt);
            }
        });

        propertiesBut.setText("Налаштування");
        propertiesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertiesButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startBut)
                                .addGap(18, 18, 18)
                                .addComponent(stopBut)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(propertiesBut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBut)
                    .addComponent(stopBut)
                    .addComponent(propertiesBut))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButActionPerformed
        RibbonStarter.starterWorker = new Thread(new RibbonStarter.ServerWorker());
        RibbonStarter.starterWorker.start();
    }//GEN-LAST:event_startButActionPerformed

    private void stopButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButActionPerformed
        RibbonStarter.starterWorker.interrupt();
        RibbonStarter.starterWorker = null;
    }//GEN-LAST:event_stopButActionPerformed

    private void propertiesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesButActionPerformed
        JDialog dialog = new PropertiesDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_propertiesButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StarterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StarterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StarterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StarterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StarterFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea journalText;
    private javax.swing.JButton propertiesBut;
    private javax.swing.JButton startBut;
    private javax.swing.JButton stopBut;
    // End of variables declaration//GEN-END:variables
}
